name       : nautilus
version    : 3.22.2
release    : 29
source     :
    - http://ftp.gnome.org/pub/gnome/sources/nautilus/3.22/nautilus-3.22.2.tar.xz : ce1c9e97173b51750521971a26943593b397a08a2736b340ef5b130095ee65b3
license    : GPL-2.0+
component  :
    - desktop.gnome
    - extension : programming.library
    - extension-devel : programming.devel
summary    : The file manager of the GNOME desktop
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gnome-autoar-0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(libnotify)
    - pkgconfig(libexif)
    - pkgconfig(exempi-2.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(shared-mime-info)
    - pkgconfig(tracker-sparql-1.0)
patterns   :
    - extension-devel :
        - /usr/include
        - /usr/lib64/lib*.so
        - /usr/lib64/pkgconfig
    - extension :
        - /usr/lib64/gi*
        - /usr/lib64/lib*.so.*
replaces   :
    - extension-devel : nautilus-devel
description: |
    The file manager of the GNOME desktop
setup      : |
    %patch -p1 < $pkgfiles/0001-Apply-sane-Solus-defaults.patch
    %reconfigure --disable-static \
                 --disable-packagekit \
                 --disable-selinux
build      : |
    %make
install    : |
    %make_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg && rmdir $installdir/etc
