name       : nautilus
version    : 3.38.2
release    : 56
source     :
    - https://download.gnome.org/sources/nautilus/3.38/nautilus-3.38.2.tar.xz : d09ceb54c274e50084c8757a73cd247fee5bde02a0b0d13733b0006d1a4196a6
license    : GPL-2.0-only
component  :
    - desktop.gnome
    - extension : programming.library
    - extension-devel : programming.devel
summary    : The file manager of the GNOME desktop
description: |
    The file manager of the GNOME desktop
builddeps  :
    - pkgconfig(gexiv2)
    - pkgconfig(gnome-autoar-0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gstreamer-tag-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libexif)
    - pkgconfig(libnotify)
    - pkgconfig(shared-mime-info)
    - tracker-devel # Change to pkgconfig(tracker-sparql-3.0) after upgrade push
    - meson
rundeps    :
    - tracker-miners
    - extension-devel :
        - nautilus-extension
    - gvfs
patterns   :
    - extension-devel :
        - /usr/include
        - /usr/lib64/lib*.so
        - /usr/lib64/pkgconfig
    - extension :
        - /usr/lib64/gi*
        - /usr/lib64/lib*.so.*
replaces   :
    - extension-devel : nautilus-devel
setup      : |
    %apply_patches
    %meson_configure \
        -Denable-exif=true \
        -Denable-gtk-doc=true \
        -Denable-packagekit=false \
        -Denable-selinux=false \
        -Denable-xmp=true
build      : |
    %ninja_build
install    : |
    %ninja_install
