name       : nautilus
version    : 3.26.2
release    : 42
source     :
    - https://download.gnome.org/sources/nautilus/3.26/nautilus-3.26.2.tar.xz : 79c99404c665ea76b3db86f261fbd28a62b54c51429b05c3314462c9de2614b4
license    : GPL-2.0
component  :
    - desktop.gnome
    - extension : programming.library
    - extension-devel : programming.devel
summary    : The file manager of the GNOME desktop
description: |
    The file manager of the GNOME desktop
builddeps  :
    - pkgconfig(exempi-2.0)
    - pkgconfig(gnome-autoar-0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(libexif)
    - pkgconfig(libnotify)
    - pkgconfig(shared-mime-info)
    - pkgconfig(tracker-sparql-2.0)
    - meson
rundeps    :
    - tracker-miners
    - extension-devel :
        - nautilus-extension
patterns   :
    - extension-devel :
        - /usr/include
        - /usr/lib64/lib*.so
        - /usr/lib64/pkgconfig
    - extension :
        - /usr/lib64/gi*
        - /usr/lib64/lib*.so.*
replaces   :
    - extension-devel : nautilus-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Apply-sane-Solus-defaults.patch
    %patch -p1 < $pkgfiles/0001-Reintroduce-Enter-Location-option.patch
    %patch -p1 < $pkgfiles/0001-Ensure-we-allow-launching-.desktop-files-with-truste.patch
    %meson_configure \
        -Denable-exif=true \
        -Denable-gtk-doc=true \
        -Denable-packagekit=false \
        -Denable-selinux=false \
        -Denable-xmp=true
build      : |
    %meson_build
install    : |
    %meson_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg && rmdir $installdir/etc
