name       : nautilus
version    : 3.28.1
release    : 45
source     :
    - https://download.gnome.org/sources/nautilus/3.28/nautilus-3.28.1.tar.xz : 9ce878fc9d9f950475c504066ce5f8e98a8cfbf15051724469e865ea85bab0a5
license    : GPL-2.0-only
component  :
    - desktop.gnome
    - extension : programming.library
    - extension-devel : programming.devel
summary    : The file manager of the GNOME desktop
description: |
    The file manager of the GNOME desktop
builddeps  :
    - pkgconfig(exempi-2.0)
    - pkgconfig(gexiv2)
    - pkgconfig(gnome-autoar-0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(libexif)
    - pkgconfig(libnotify)
    - pkgconfig(shared-mime-info)
    - pkgconfig(tracker-sparql-2.0)
    - meson
rundeps    :
    - tracker-miners
    - extension-devel :
        - nautilus-extension
patterns   :
    - extension-devel :
        - /usr/include
        - /usr/lib64/lib*.so
        - /usr/lib64/pkgconfig
    - extension :
        - /usr/lib64/gi*
        - /usr/lib64/lib*.so.*
replaces   :
    - extension-devel : nautilus-devel
setup      : |
    export CFLAGS="${CFLAGS} -Wno-error=maybe-uninitialized"
    %apply_patches
    %meson_configure \
        -Ddocs=true \
        -Dpackagekit=false \
        -Dselinux=false
build      : |
    %ninja_build
install    : |
    %ninja_install
