name        : nautilus
version     : 3.18.5
release     : 21
source     :
    - http://ftp.gnome.org/pub/gnome/sources/nautilus/3.18/nautilus-3.18.5.tar.xz : 60a927c0522b4cced9d8f62baed2ee5e2fd4305be4523eb5bc44805971a6cc15
license     : GPL-2.0+
summary     : The file manager of the GNOME desktop
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(packagekit-glib2)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(libnotify)
    - pkgconfig(libexif)
    - pkgconfig(exempi-2.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(shared-mime-info)
description : |
    The file manager of the GNOME desktop
setup      : |
    %patch -p1 < $pkgfiles/0001-Sane-sensible-defaults.patch
    %patch -p1 < $pkgfiles/restore_delete_setting.patch
    %patch -p1 < $pkgfiles/0001-Show-the-Delete-Permanently-option-by-default-in-Sol.patch
    %configure --disable-tracker \
               --disable-static \
               --enable-packagekit
build      : |
    %make
install    : |
    %make_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg && rmdir $installdir/etc
