name        : nautilus
version     : 3.18.2
release     : 16
source     :
    - http://ftp.gnome.org/pub/gnome/sources/nautilus/3.18/nautilus-3.18.2.tar.xz : 68dcf668e2ca93126a899d2e236ef37af2aea93e3fc25eee23ccd7ba911d424a
license     : GPL-2.0+
summary     : The file manager of the GNOME desktop
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(packagekit-glib2)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(libnotify)
    - pkgconfig(libexif)
    - pkgconfig(exempi-2.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(shared-mime-info)
description : |
    The file manager of the GNOME desktop
setup      : |
    %patch -p1 < $pkgfiles/0001-Sane-sensible-defaults.patch
    %configure --disable-tracker \
               --disable-static \
               --enable-packagekit
build      : |
    %make
install    : |
    %make_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg && rmdir $installdir/etc
