name       : nautilus
version    : 3.24.0
release    : 34
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/nautilus/3.24/nautilus-3.24.0.tar.xz : 8a499247caff3c02437c0ad955f043e675a056912d8553d9c9783c762f5dbbbd
license    : GPL-2.0
component  :
    - desktop.gnome
    - extension : programming.library
    - extension-devel : programming.devel
summary    : The file manager of the GNOME desktop
description: |
    The file manager of the GNOME desktop
builddeps  :
    - pkgconfig(exempi-2.0)
    - pkgconfig(gnome-autoar-0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libexif)
    - pkgconfig(libnotify)
    - pkgconfig(shared-mime-info)
patterns   :
    - extension-devel :
        - /usr/include
        - /usr/lib64/lib*.so
        - /usr/lib64/pkgconfig
    - extension :
        - /usr/lib64/gi*
        - /usr/lib64/lib*.so.*
replaces   :
    - extension-devel : nautilus-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Apply-sane-Solus-defaults.patch
    %patch -p1 < $pkgfiles/0001-Reintroduce-Enter-Location-option.patch
    %reconfigure --disable-static \
                 --disable-packagekit \
                 --disable-selinux \
                 --disable-tracker
build      : |
    %make
install    : |
    %make_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg && rmdir $installdir/etc
