name       : nautilus
version    : '40.1'
release    : 58
source     :
    - https://download.gnome.org/sources/nautilus/40/nautilus-40.1.tar.xz : 8ecfb90174a0bd5815b1ceb9cbfcd91fec0fb5e34907a4f2df2d05e5d6c99d33
license    : GPL-2.0-only
component  :
    - desktop.gnome
    - extension : programming.library
    - extension-devel : programming.devel
summary    : The file manager of the GNOME desktop
description: |
    The file manager of the GNOME desktop
builddeps  :
    - pkgconfig(gexiv2)
    - pkgconfig(gnome-autoar-0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gstreamer-tag-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libexif)
    - pkgconfig(libnotify)
    - pkgconfig(libportal)
    - pkgconfig(shared-mime-info)
    - pkgconfig(tracker-sparql-3.0)
    - meson
rundeps    :
    - tracker-miners
    - extension-devel :
        - nautilus-extension
    - gvfs
patterns   :
    - extension-devel :
        - /usr/include
        - /usr/lib64/lib*.so
        - /usr/lib64/pkgconfig
    - extension :
        - /usr/lib64/gi*
        - /usr/lib64/lib*.so.*
replaces   :
    - extension-devel : nautilus-devel
setup      : |
    %apply_patches
    %meson_configure \
        -Denable-exif=true \
        -Denable-gtk-doc=true \
        -Denable-packagekit=false \
        -Denable-selinux=false \
        -Denable-xmp=true
build      : |
    %ninja_build
install    : |
    %ninja_install
