name       : nautilus
version    : 3.26.4
release    : 52
source     :
    - https://download.gnome.org/sources/nautilus/3.26/nautilus-3.26.4.tar.xz : a22d9c8fd759f594039090b2fdb3bb3c87e314eff6d320a007a79b1f513b8ae0
license    : GPL-2.0-only
component  :
    - desktop.gnome
    - extension : programming.library
    - extension-devel : programming.devel
summary    : The file manager of the GNOME desktop
description: |
    The file manager of the GNOME desktop
builddeps  :
    - pkgconfig(exempi-2.0)
    - pkgconfig(gnome-autoar-0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(libexif)
    - pkgconfig(libnotify)
    - pkgconfig(shared-mime-info)
    - pkgconfig(tracker-sparql-2.0)
    - meson
rundeps    :
    - tracker-miners
    - extension-devel :
        - nautilus-extension
    - gvfs
patterns   :
    - extension-devel :
        - /usr/include
        - /usr/lib64/lib*.so
        - /usr/lib64/pkgconfig
    - extension :
        - /usr/lib64/gi*
        - /usr/lib64/lib*.so.*
replaces   :
    - extension-devel : nautilus-devel
setup      : |
    %apply_patches
    %meson_configure \
        -Denable-exif=true \
        -Denable-gtk-doc=true \
        -Denable-packagekit=false \
        -Denable-selinux=false \
        -Denable-xmp=true
build      : |
    %ninja_build
install    : |
    # Stateless XDG
    %ninja_install
    mv $installdir/etc/xdg $installdir/usr/share/xdg && rmdir $installdir/etc
