name       : nautilus
version    : '42.2'
release    : 66
source     :
    - https://download.gnome.org/sources/nautilus/42/nautilus-42.2.tar.xz : 99212d2eb75996f181728ad04a2e2d86f2577b064e68a34c8b81a7037df4ccb2
homepage   : https://wiki.gnome.org/action/show/Apps/Files
license    : GPL-2.0-only
component  :
    - desktop.gnome
    - extension : programming.library
    - extension-devel : programming.devel
summary    : The file manager of the GNOME desktop
description: |
    The file manager of the GNOME desktop
builddeps  :
    - pkgconfig(gexiv2)
    - pkgconfig(gnome-autoar-0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gstreamer-tag-1.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(libexif)
    - pkgconfig(libhandy-1)
    - pkgconfig(libnotify)
    - pkgconfig(shared-mime-info)
    - pkgconfig(tracker-sparql-3.0)
    - meson
rundeps    :
    - tracker-miners
    - extension-devel :
        - nautilus-extension
    - gvfs
patterns   :
    - extension-devel :
        - /usr/include
        - /usr/lib64/lib*.so
        - /usr/lib64/pkgconfig
    - extension :
        - /usr/lib64/gi*
        - /usr/lib64/lib*.so.*
replaces   :
    - extension-devel : nautilus-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Apply-sane-Solus-defaults.patch
    %meson_configure \
        -Ddocs=true \
        -Dlibportal=false \
        -Dpackagekit=false \
        -Dselinux=false
build      : |
    %ninja_build
install    : |
    %ninja_install
