name       : nautilus
version    : 3.20.1
release    : 23
source     :
    - http://ftp.gnome.org/pub/gnome/sources/nautilus/3.20/nautilus-3.20.1.tar.xz : f2a907b994026412a7ed7c8145d4ab4f886ac87e780353b967473305a35e81e8
license    : GPL-2.0+
component  : desktop.gnome
summary    : The file manager of the GNOME desktop
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(libnotify)
    - pkgconfig(libexif)
    - pkgconfig(exempi-2.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(shared-mime-info)
description: |
    The file manager of the GNOME desktop
setup      : |
    %patch -p1 < $pkgfiles/0001-Sane-sensible-defaults.patch
    %patch -p1 < $pkgfiles/0001-Show-the-Delete-Permanently-option-by-default-in-Sol.patch
    %patch -p1 < $pkgfiles/0001-Make-icon-chooser-dialog-modal.patch
    %configure --disable-tracker \
               --disable-static \
               --disable-packagekit \
               --disable-selinux
build      : |
    %make
install    : |
    %make_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg && rmdir $installdir/etc
